//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sahira_Hotel_Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BookingHotels = new HashSet<BookingHotel>();
            this.BookingTrips = new HashSet<BookingTrip>();
        }
    
        public string id_customer { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.DateTime dob { get; set; }
        public string nationality { get; set; }
        public int id_customerType { get; set; }
    
        public virtual ICollection<BookingHotel> BookingHotels { get; set; }
        public virtual ICollection<BookingTrip> BookingTrips { get; set; }
        public virtual CustomerType CustomerType { get; set; }
    }
}
