//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sahira_Hotel_Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripPackageDetail
    {
        public int id_package_detail { get; set; }
        public int id_package { get; set; }
        public string id_trip { get; set; }
    
        public virtual TripDestination TripDestination { get; set; }
        public virtual TripPackage TripPackage { get; set; }
    }
}
