//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sahira_Hotel_Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripSchedule
    {
        public int id_schedule { get; set; }
        public int id_package { get; set; }
        public string pic { get; set; }
        public string tour_guide { get; set; }
        public string driver { get; set; }
        public int capacity { get; set; }
    
        public virtual TripPackage TripPackage { get; set; }
    }
}
