//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sahira_Hotel_Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDestination
    {
        public TripDestination()
        {
            this.Galleries = new HashSet<Gallery>();
        }
    
        public int id_trip { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int id_region { get; set; }
        public string description { get; set; }
        public double localPrice { get; set; }
        public Nullable<double> internationalPrice { get; set; }
        public int id_package { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual Region Region { get; set; }
        public virtual TripPackage TripPackage { get; set; }
    }
}
